version: 0.2

 phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven and AWS CLI
      - yum install -y maven awscli curl
      - echo Build environment ready

  pre_build:
    commands:
      - echo Pre-build phase started
      - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
      - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
      - aws configure set default.region ap-south-1
      - echo Pre-build phase complete

  build:
    commands:
      - echo Building the WAR file
      - mvn clean package
      - echo WAR build complete

  post_build:
    commands:
      - echo Post-build phase started

      # Deploy to Tomcat
      - |
        echo Deploying to Tomcat
        WAR_FILE="target/Ecomm.war"

        if [[ -z "$TOMCAT_URL" ]]; then
          echo "Error: TOMCAT_URL environment variable is not set"
          exit 1
        fi

        FULL_DEPLOY_URL="${TOMCAT_URL}/manager/text/deploy?path=/Ecomm&update=true"

        echo "Deploying ${WAR_FILE} to: ${FULL_DEPLOY_URL}"

        curl -v -u "${TOMCAT_USER}:${TOMCAT_PASSWORD}" \
          -T "${WAR_FILE}" \
          "${FULL_DEPLOY_URL}"

      # Upload WAR to S3
      - |
        echo Uploading WAR to S3
        aws s3 cp target/Ecomm.war s3://my-bucket-ecomm/Ecomm.war

      # Send SNS Notification
      - |
        echo Sending SNS notification
        aws sns publish \
          --topic-arn "$SNS_TOPIC_ARN" \
          --subject "🚀 Deployment Complete" \
          --message "WAR file deployed to Tomcat and uploaded to S3 successfully."

artifacts:
  files:
    - target/Ecomm.war
