name: Java CI/CD with WAR to Tomcat and then S3

on:
  push:
    branches: [ "master" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build WAR with Maven
      run: mvn clean package

    - name: Deploy to Tomcat
      run: |
        TOMCAT_DEPLOY_BASE_URL="${{ secrets.TOMCAT_URL }}"
        TOMCAT_USER="${{ secrets.TOMCAT_USERNAME }}"
        TOMCAT_PASS="${{ secrets.TOMCAT_PASSWORD }}"
        WAR_FILE="target/Ecomm.war"

        if [[ -z "$TOMCAT_DEPLOY_BASE_URL" ]]; then
          echo "Error: The 'TOMCAT_URL' secret is empty. Please set it correctly in your GitHub repository secrets."
          exit 1
        fi

        
        - name: Start Tomcat Server
        run: |
          /opt/tomcat/bin/startup.sh
          sleep 10

        FULL_DEPLOY_URL="${TOMCAT_DEPLOY_BASE_URL}&update=true"

        echo "Attempting to deploy ${WAR_FILE} to: ${FULL_DEPLOY_URL}"

        curl -v -u "${TOMCAT_USER}":"${TOMCAT_PASS}" \
        -T "${WAR_FILE}" \
        "${FULL_DEPLOY_URL}"

    - name: Upload WAR to S3 (after Tomcat deployment)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure set default.region ap-south-1
        echo "Uploading target/Ecomm.war to s3://my-app-deploy-bucket/Ecomm.war"
        aws s3 cp target/Ecomm.war s3://my-app-deploy-bucket/Ecomm.war
