
name: Build and Push Docker Image to Docker Hub and ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: myecommapp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # change if using a different region

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker tags
        id: vars
        run: |
          TAG=latest
          DOCKER_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:$TAG
          ECR_IMAGE=${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:$TAG
          echo "docker_image=${DOCKER_IMAGE}" >> $GITHUB_OUTPUT
          echo "ecr_image=${ECR_IMAGE}" >> $GITHUB_OUTPUT

      - name: Build multi-stage Docker image
        run: |
          docker build -t ${{ steps.vars.outputs.docker_image }} -t ${{ steps.vars.outputs.ecr_image }} .

      - name: Push to Docker Hub
        run: docker push ${{ steps.vars.outputs.docker_image }}

      - name: Push to Amazon ECR
        run: docker push ${{ steps.vars.outputs.ecr_image }}
